### ISSUE TITLE
todo: Task Lists 

### ISSUE THREAD

**Issue by Klairm** [Klairm/Linux-Gaming-Setup#17]
# Overview

Will list here the tasks left to do in a list for more productivity.

### Features

- [ ] Fedora support
- [ ] Debian drivers installation
- [ ] Finish error handlers

### Future ideas
- [ ] Create a GUI version
- [ ] \(Optional) Provide as an distributable file when GUI is finished 
- [ ] \(Optional) not sure: Should  all of this be ported to bash?
- [ ] \(Optional) not sure: Add custom kernel installation for example linux-tkg or zen #6
